name: Build and Deploy

on:
	push:
		branches:
		- main
		
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore dependencies
        run: npm install

      - name: Build solution
        run: npm run build

      - name: Deploy to Azure
		    uses: azure/webapps-deploy@v2
		    with:
			    app-name: omaTestiVite
			    slot-name: production
			    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
			    package: dist